### ISSUE TITLE
Running on Wokwi

### ISSUE THREAD

**Issue by manupawickramasinghe** [raspiduino/arv32-opt#1]
<img width="403" alt="image" src="https://github.com/raspiduino/arv32-opt/assets/73810867/2fb39217-d08e-4af7-b024-a2af61037337">

I Have no idea on fixing this.

**Comment by raspiduino** [comment]
Why did you close the issue?

BTW I think the issue is likely because the SD implementation is a dirty hack (for example I sent CMD manually) instead of using any standard SD library, so if Wokwi does not emulate stuff to *that* low level, it won't run.
